#!/usr/bin/with-contenv /bin/sh

cat > /usr/share/phpci/PHPCI/config.yml << EOF
b8:
    database:
        servers:
            read: ${PHPCI_DB_HOST}
            write: ${PHPCI_DB_HOST}
        name: ${PHPCI_DB_NAME}
        username: ${PHPCI_DB_USER}
        password: ${PHPCI_DB_PASSWORD}
phpci:
    url: "${PHPCI_URL:-http://$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1 }')}"
    worker:
        host: ${PHPCI_QUEUE_HOST:-beanstalkd}
        queue: ${PHPCI_QUEUE_NAME:-phpci}
EOF
