version: '2.3'

services:

    beanstalkd:
        command: 'beanstalkd'
        image: 'timonier/beanstalkd:latest'
        init: true

    master:
        build:
            context: ./src/master
            dockerfile: ./src/master/Dockerfile
        environment:
            - 'PHPCI_DB_HOST=mysql'
            - 'PHPCI_DB_NAME=phpci'
            - 'PHPCI_DB_PASSWORD=ThisPasswordIsNotSoSecretChangeIt'
            - 'PHPCI_DB_USER=phpci'
            - 'PHPCI_QUEUE_HOST=beanstalkd'
            - 'PHPCI_QUEUE_NAME=phpci'
        image: 'timonier/phpci:master'
        volumes:
            - 'phpci-data:/home/www-data:rw'

    mysql:
        command: '--sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,ONLY_FULL_GROUP_BY"'
        environment:
            - 'MYSQL_DATABASE=phpci'
            - 'MYSQL_PASSWORD=ThisPasswordIsNotSoSecretChangeIt'
            - 'MYSQL_ROOT_PASSWORD=ThisPasswordIsNotSoSecretChangeIt'
            - 'MYSQL_USER=phpci'
        image: 'timonier/mysql:latest'
        init: true
        volumes:
            - 'mysql-data:/var/lib/mysql:rw'

    worker:
        build:
            context: ./src/worker
            dockerfile: ./src/worker/Dockerfile
        environment:
            - 'PHPCI_DB_HOST=mysql'
            - 'PHPCI_DB_NAME=phpci'
            - 'PHPCI_DB_PASSWORD=ThisPasswordIsNotSoSecretChangeIt'
            - 'PHPCI_DB_USER=phpci'
            - 'PHPCI_QUEUE_HOST=beanstalkd'
            - 'PHPCI_QUEUE_NAME=phpci'
        image: timonier/phpci:worker
        volumes:
            - 'phpci-data:/home/www-data:rw'

volumes:

    mysql-data: {}

    phpci-data: {}
